version: "2"
linters:
  default: all
  disable:
    # k6 extensions must be registered from the init() function.
    - gochecknoinits

    # The constructor of k6 extensions must return an interface.
    - ireturn

    # In many cases (e.g. options) it is normal usage not to specify all structure fields.
    - exhaustruct

    # Many go standard library API functions have typical parameter names shorter than 3 characters.
    # It is better to use the usual parameter names than to create one that conforms to the rule.
    - varnamelen

    # Except for general-purpose public APIs,
    # wrapping errors is more inconvenient and error prone than useful.
    - wrapcheck

    # The k6 extension API is not a general-purpose API.
    - testpackage

    # Would require rewriting a lot of code.
    - noinlineerr

    # Deprecated
    - wsl
  exclusions:
    rules:
      - linters:
          - gosec
        # context cancellation function not called directly, but stored in a variable and called indirectly.
        text: "G118:"
  settings:
    depguard:
      rules:
        prevent_accidental_imports:
          allow:
            - $gostd
            - github.com/stretchr/testify/require
            - go.k6.io/k6
            - github.com/grafana/sobek
            - github.com/mstoykov/k6-taskqueue-lib/taskqueue
            - github.com/grafana/xk6-tcp
            - github.com/sirupsen/logrus

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
