/**
 * **TCP Protocol Extension for k6**
 *
 * This extension provides TCP socket functionality for k6 performance testing scripts,
 * offering both synchronous and asynchronous APIs for network communication.
 *
 * @module k6/x/tcp
 * @example
 * ```typescript
 * import { Socket } from 'k6/x/tcp';
 *
 * const socket = new Socket();
 * socket.connect(8080, 'example.com');
 * socket.write('Hello, server!', {
 *   tags: { message_type: 'greeting' }
 * });
 * ```
 */
declare module "k6/x/tcp" {
  /**
   * Configuration options for creating a new TCP socket.
   *
   * @example
   * ```typescript
   * const socket = new Socket({
   *   tags: { endpoint: 'api', environment: 'prod' }
   * });
   * ```
   */
  export interface SocketOptions {
    /**
     * Optional key-value pairs for metrics collection and logging.
     * These tags will be attached to all metrics generated by this socket.
     */
    tags?: Record<string, string>;
  }

  /**
   * Represents the current state of a TCP socket connection.
   * These states correspond to the socket lifecycle from creation to destruction.
   */
  export type SocketState =
    | 'opening'       // Socket is in the process of establishing a connection
    | 'open'          // Socket is connected and ready for bidirectional communication
    | 'destroyed'     // Socket has been destroyed and is unusable
    | 'disconnected'; // Socket is not connected to any remote endpoint

  /**
   * Events that can be emitted by a TCP socket during its lifecycle.
   * Use these with the `on()` method to handle socket events.
   */
  export type SocketEvent =
    | 'connect'    // Emitted when the socket successfully establishes a connection
    | 'data'       // Emitted when data is received from the remote endpoint
    | 'close'      // Emitted when the socket connection is fully closed
    | 'error'      // Emitted when a socket error occurs
    | 'timeout';   // Emitted when the socket times out due to inactivity

  /**
   * Configuration options for establishing a TCP socket connection.
   *
   * @example
   * ```typescript
   * // Basic connection
   * socket.connect({
   *   port: 8080,
   *   host: 'api.example.com',
   *   tags: { service: 'api-server' }
   * });
   * 
   * // Secure TLS connection
   * socket.connect({
   *   port: 443,
   *   host: 'secure.example.com',
   *   tls: true,
   *   tags: { protocol: 'tls' }
   * });
   * ```
   */
  export interface ConnectOptions {
    /** The destination port number (1-65535) */
    port: number;
    /** The destination hostname or IP address. Defaults to 'localhost' */
    host?: string;
    /**
     * Enable TLS/SSL encryption for this connection.
     * 
     * When enabled, the socket will perform a TLS handshake after establishing
     * the TCP connection. TLS configuration (certificates, verification, etc.)
     * is controlled by k6's standard TLS settings.
     * 
     * @see https://grafana.com/docs/k6/latest/using-k6/protocols/ssl-tls/
     * @default false
     */
    tls?: boolean;
    /**
     * Optional key-value pairs for metrics collection and logging.
     * These tags will be attached to connection-related metrics.
     *
     * This is provided for convenience since tags can also be specified
     * during socket creation via SocketOptions. Tags specified here will
     * override tags with the same name specified when creating the socket.
     */
    tags?: Record<string, string>;
  }

  /**
   * Configuration options for writing data to a TCP socket.
   *
   * @example
   * ```typescript
   * // Write with encoding and tags
   * socket.write('SGVsbG8gV29ybGQ=', {
   *   encoding: 'base64',
   *   tags: { operation: 'send-auth-token' }
   * });
   * ```
   */
  export interface WriteOptions {
    /**
     * The encoding to use when data is a string.
     * Common encodings include 'utf8', 'ascii', 'base64', 'hex'.
     * Defaults to 'utf8' if not specified.
     */
    encoding?: string;
    /**
     * Optional key-value pairs for metrics collection and logging.
     * These tags will be attached to write-related metrics for this specific operation.
     *
     * Tags specified here will be merged with socket-level and connection-level tags.
     * Operation-level tags take highest priority for duplicate keys.
     */
    tags?: Record<string, string>;
  }

  /**
   * TCP Socket implementation for k6 performance testing.
   *
   * Provides a Node.js-compatible API for TCP socket operations, adapted for the k6 environment.
   * Supports both synchronous and asynchronous operations with comprehensive event handling.
   *
   * @example
   * ```typescript
   * import { Socket } from 'k6/x/tcp';
   *
   * const socket = new Socket();
   *
   * socket.on('connect', () => {
   *   console.log('Connected to server');
   *   socket.write('Hello, World!', {
   *     tags: { message_type: 'greeting' }
   *   });
   * });
   *
   * socket.on('data', (data) => {
   *   console.log('Received:', new TextDecoder().decode(data));
   * });
   *
   * socket.connect(8080, 'example.com');
   * ```
   */
  export class Socket {
    /**
     * The current state of the socket connection.
     *
     * Provides detailed information about the socket's lifecycle state,
     * similar to Node.js net.Socket readyState.
     *
     * @example
     * ```typescript
     * console.log('Socket state:', socket.ready_state);
     * // Output: 'disconnected', 'opening', 'open', etc.
     * ```
     */
    ready_state: SocketState;

    /**
     * The string representation of the local IP address the remote client
     * is connecting on.
     */
    local_ip?: string;

    /**
     * The numeric representation of the local port.
     */
    local_port?: number;

    /**
     * The string representation of the remote IP address.
     */
    remote_ip?: string;

    /**
     * The numeric representation of the remote port.
     */
    remote_port?: number;

    /**
     * The number of bytes sent.
     */
    bytes_written: number;

    /**
     * The number of bytes received.
     */
    bytes_read: number;

    /**
     * Indicates whether the socket is currently connected to a remote endpoint.
     *
     * This is a convenience property that returns `true` when `ready_state` is `'open'`,
     * and `false` otherwise. It provides a simple boolean check for connection status.
     *
     * @example
     * ```typescript
     * if (socket.connected) {
     *   socket.write('Hello!');
     * } else {
     *   console.log('Socket not connected');
     * }
     * ```
     */
    readonly connected: boolean;

    /**
     * Creates a new TCP socket instance.
     *
     * The socket is created in a disconnected state. Use `connect()` to establish a connection.
     *
     * @param options Optional configuration for the socket
     * @example
     * ```typescript
     * // Create a basic socket
     * const socket = new Socket();
     *
     * // Create a socket with tags for metrics
     * const taggedSocket = new Socket({
     *   tags: { component: 'api-client', version: '1.0' }
     * });
     * ```
     */
    constructor(options?: SocketOptions);

    /**
     * Initiates a TCP connection to the specified host and port.
     *
     * This method is non-blocking and returns immediately. Listen for the 'connect'
     * event to know when the connection is established, or 'error' for failures.
     *
     * @param port The destination port number (1-65535)
     * @param host The destination hostname or IP address (defaults to 'localhost')
     * @returns The socket instance for method chaining
     * @example
     * ```typescript
     * socket.on('connect', () => console.log('Connected!'));
     * socket.on('error', (err) => console.error('Connection failed:', err));
     * socket.connect(8080, 'api.example.com');
     * ```
     */
    connect(port: number, host?: string): this;

    /**
     * Initiates a TCP connection using detailed connection options.
     *
     * This method is non-blocking and returns immediately. Listen for the 'connect'
     * event to know when the connection is established, or 'error' for failures.
     *
     * @param options Comprehensive connection configuration
     * @returns The socket instance for method chaining
     * @example
     * ```typescript
     * socket.on('connect', () => console.log('Connected!'));
     * socket.connect({
     *   port: 8080,
     *   host: 'api.example.com',
     *   tags: { endpoint: 'api-server' }
     * });
     * ```
     */
    connect(options: ConnectOptions): this;

    /**
     * Asynchronously initiate a connection on a given socket.
     * Returns a Promise that resolves when the connection is established.
     * @param port The port number to connect to
     * @param host The host to connect to. Defaults to 'localhost'
     * @returns A Promise that resolves when connected successfully
     * @example
     * ```typescript
     * await socket.connectAsync(8080, 'example.com');
     * console.log('Connected to server');
     * ```
     */
    connectAsync(port: number, host?: string): Promise<void>;

    /**
     * Asynchronously initiate a connection on a given socket with options.
     * Returns a Promise that resolves when the connection is established.
     * @param options Connection options including port, host, and other settings
     * @returns A Promise that resolves when connected successfully
     * @example
     * ```typescript
     * await socket.connectAsync({
     *   port: 8080,
     *   host: 'example.com'
     * });
     * console.log('Connected to server');
     * ```
     */
    connectAsync(options: ConnectOptions): Promise<void>;

    /**
     * Sends data on the socket with additional options.
     * @param data The data to write - can be a string or ArrayBuffer for binary data
     * @param options Optional configuration options for the write operation
     * @returns `true` if the data was flushed successfully
     * @example
     * ```typescript
     * // Write with encoding
     * socket.write('SGVsbG8gV29ybGQ=', { encoding: 'base64' });
     *
     * // Write with tags for metrics
     * socket.write('Hello, server!', {
     *   tags: { operation: 'handshake', protocol: 'custom' }
     * });
     *
     * // Write with both encoding and tags
     * socket.write('encoded-payload', {
     *   encoding: 'hex',
     *   tags: { data_type: 'binary', size: 'small' }
     * });
     * ```
     */
    write(data: string | ArrayBuffer, options?: WriteOptions): boolean;

    /**
     * Asynchronously sends data on the socket with additional options.
     * Returns a Promise that resolves when the data has been written to the socket.
     * @param data The data to write - can be a string or ArrayBuffer for binary data
     * @param options Optional configuration options for the write operation
     * @returns A Promise that resolves when the data has been successfully written
     * @example
     * ```typescript
     * // Write with encoding
     * await socket.writeAsync('SGVsbG8gV29ybGQ=', { encoding: 'base64' });
     *
     * // Write with tags for metrics
     * await socket.writeAsync('Hello, server!', {
     *   tags: { operation: 'handshake', protocol: 'custom' }
     * });
     *
     * // Write with both encoding and tags
     * await socket.writeAsync('encoded-payload', {
     *   encoding: 'hex',
     *   tags: { data_type: 'binary', size: 'small' }
     * });
     * ```
     */
    writeAsync(data: string | ArrayBuffer, options?: WriteOptions): Promise<void>;

    /**
     * Destroys the socket. Once a socket is destroyed, no further communication is possible.
     * @param error Optional error to emit with `error` event
     * @returns The socket itself for method chaining
     */
    destroy(error?: Error): this;

    /**
     * Sets the socket timeout for inactivity.
     *
     * Sets the socket to timeout after `timeout` milliseconds of inactivity on the socket.
     * By default, TCP sockets do not have a timeout. When an idle timeout is triggered,
     * the socket will receive a 'timeout' event but the connection will not be severed.
     * The user must manually call `destroy()` to end the connection.
     *
     * If `timeout` is 0, then the existing idle timeout is disabled.
     *
     * @param timeout Timeout duration in milliseconds. Use 0 to disable timeout
     * @returns The socket instance for method chaining
     * @example
     * ```typescript
     * // Set a 30-second timeout
     * socket.setTimeout(30000);
     * socket.on('timeout', () => {
     *   console.log('Socket timed out');
     *   socket.destroy();
     * });
     *
     * // Disable timeout
     * socket.setTimeout(0);
     * ```
     */
    setTimeout(timeout: number): this;

    /**
     * Registers an event listener for the 'connect' event.
     *
     * The 'connect' event is emitted when the socket successfully establishes
     * a connection to the remote server. This indicates the socket is ready
     * for reading and writing data.
     *
     * **Important:** Only one listener is supported per event type.
     * Calling this method multiple times will replace the previously set listener.
     *
     * @param event The event name 'connect'
     * @param listener Callback function invoked when the connection is established
     * @returns The socket instance for method chaining
     * @example
     * ```typescript
     * socket.on('connect', () => {
     *   console.log('Connected! Ready to send data.');
     *   socket.write('Hello, server!');
     * });
     * ```
     */
    on(event: 'connect', listener: () => void): this;

    /**
     * Registers an event listener for the 'data' event.
     *
     * The 'data' event is emitted when data is received from the remote endpoint.
     * The data is provided as an ArrayBuffer for efficient binary data handling.
     *
     * **Important:** Only one listener is supported per event type.
     * Calling this method multiple times will replace the previously set listener.
     *
     * @param event The event name 'data'
     * @param listener Callback function invoked when data is received
     * @returns The socket instance for method chaining
     * @example
     * ```typescript
     * socket.on('data', (data) => {
     *   const text = new TextDecoder().decode(data);
     *   console.log('Received:', text);
     *
     *   // Or handle binary data directly
     *   const bytes = new Uint8Array(data);
     *   console.log('Binary data:', bytes);
     * });
     * ```
     */
    on(event: 'data', listener: (data: ArrayBuffer) => void): this;

    /**
     * Registers an event listener for the 'close' event.
     *
     * The 'close' event is emitted when the socket connection is fully closed
     * by either the local or remote endpoint. This is the final event in the
     * socket lifecycle.
     *
     * **Important:** Only one listener is supported per event type.
     * Calling this method multiple times will replace the previously set listener.
     *
     * @param event The event name 'close'
     * @param listener Callback function invoked when the socket closes, receives a boolean indicating if an error occurred
     * @returns The socket instance for method chaining
     * @example
     * ```typescript
     * socket.on('close', (hadError) => {
     *   if (hadError) {
     *     console.log('Socket closed due to an error');
     *   } else {
     *     console.log('Socket closed normally');
     *   }
     * });
     * ```
     */
    on(event: 'close', listener: (had_error: boolean) => void): this;

    /**
     * Registers an event listener for the 'error' event.
     *
     * The 'error' event is emitted when a socket error occurs, such as
     * connection failures, network issues, or protocol errors. It's crucial
     * to handle this event to prevent unhandled errors.
     *
     * **Important:** Only one listener is supported per event type.
     * Calling this method multiple times will replace the previously set listener.
     *
     * @param event The event name 'error'
     * @param listener Callback function invoked when an error occurs, receives the Error object
     * @returns The socket instance for method chaining
     * @example
     * ```typescript
     * socket.on('error', (error) => {
     *   console.error('Connection failed:', error.message);
     *   // Handle the error appropriately
     *   socket.destroy();
     * });
     * ```
     */
    on(event: 'error', listener: (error: Error) => void): this;

    /**
     * Registers an event listener for the 'timeout' event.
     *
     * The 'timeout' event is emitted when the socket times out due to inactivity
     * as configured by `setTimeout()`. Note that the socket is not automatically
     * destroyed after a timeout - you must manually call `destroy()` if needed.
     *
     * **Important:** Only one listener is supported per event type.
     * Calling this method multiple times will replace the previously set listener.
     *
     * @param event The event name 'timeout'
     * @param listener Callback function invoked when the socket times out
     * @returns The socket instance for method chaining
     * @example
     * ```typescript
     * socket.setTimeout(30000); // Set 30-second timeout
     * socket.on('timeout', () => {
     *   console.log('Connection timed out after 30 seconds');
     *   socket.destroy(); // Manually close the socket
     * });
     * ```
     */
    on(event: 'timeout', listener: () => void): this;
  }
}
